### ISSUE TITLE
CMYK value

### ISSUE THREAD

**Issue by sasharevzin** [jordanstephens/paleta#5]
It will be nice to get CMYK as well. 

Check this piece of code that converts from RGB to CMYK:

```javascript
function (RGB){
        var result = {c: 0, m: 0, y: 0, k: 0};
 
        r = RGB.r / 255;
        g = RGB.g / 255;
        b = RGB.b / 255;
 
        result.k = Math.min( 1 - r, 1 - g, 1 - b );
        result.c = ( 1 - r - result.k ) / ( 1 - result.k );
        result.m = ( 1 - g - result.k ) / ( 1 - result.k );
        result.y = ( 1 - b - result.k ) / ( 1 - result.k );
 
        result.c = Math.round( result.c * 100 );
        result.m = Math.round( result.m * 100 );
        result.y = Math.round( result.y * 100 );
        result.k = Math.round( result.k * 100 );
 
        return result;
    }
```

**Comment by jordanstephens** [comment]
I'm not keen on the details of this specific conversion method which you have presented, but I was under the impression that translation from RGB to CMYK was in general not a good idea—or at the very least, not so simple. The reason for this being that the total spectrum of color represented in each space is not the same. In other words, there are colors which may be represented with RGB, but which cannot be represented with CMYK—and vice versa. The simplicity of the function above suggests that this consideration has not been taken into account, or that the results may be skewed, or that the results may be otherwise incorrect. It seems like there must be some case where the result would have to be undefined, or an exception would need to be raised.

For now, I don't think I am confident enough to implement such a conversion strategy to a degree of quality which would be satisfactory.

I'm happy to hear more thoughts on this, however—maybe I'm wrong.

**Comment by nadavshatz** [comment]
@jordanstephens this can probably be closed.

**Comment by jordanstephens** [comment]
Cool, I will close this for now.
